name: Build and test

on: [push]

jobs:
    build-and-test-linux:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04]
        steps:
            - uses: actions/checkout@v1
            - name: Running CMake...
              run: mkdir build && cd build && cmake -G "Unix Makefiles" ..
            - name: Building...
              run: cd build && make all
            - name: Testing...
              run: cd build && make test
