name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: make libelrond.a 
      run: make libelrond.a
    - name: make test-all
      run: make test-all
