name: Build and test

on: [push]

jobs:
    build-and-test-macos:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, macos-10.15]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run CMake
              run: cmake -H. -B./build -G "Unix Makefiles"
            - name: Build everything
              run: cmake --build ./build --target all -j 6 --
            - name: Run tests
              run: ctest -j6 -T test --output-on-failure --test-dir ./build

    build-and-test-linux:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run CMake
              run: cmake -H. -B./build -G "Unix Makefiles"
            - name: Build everything
              run: cmake --build ./build --target all -j 6 --
            - name: Run tests
              run: ctest -j6 -T test --output-on-failure --test-dir ./build
