name: Build and test

on: [push]

jobs:
    build-and-test-macos:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, macos-11, ubuntu-18.04]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run CMake
              run: cmake -B./build -G "Unix Makefiles" .
            - name: Build everything
              run: cmake --build ./build --target all -j 6 --
            - name: Run tests
              run: ctest -j6 -T test --output-on-failure --test-dir ./build

    build-and-test-windows:
        name: Build and test on ${{matrix.os}} (${{matrix.arch}})
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, windows-2022]
                arch: [amd64, x86]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Start VCTools
              uses: seanmiddleditch/gha-setup-vsdevenv@master
              with:
                arch: ${{matrix.arch}}
            - name: Run CMake
              run: cmake -B.\build -G "NMake Makefiles" .
            - name: Build everything
              run: cmake --build ./build --target all --
            - name: Run tests
              run: ctest -j6 -T test --output-on-failure --test-dir ./build
