name: build_and_test

on: [push]

jobs:
    build-and-test-linux:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04]
        steps:
            - uses: actions/checkout@v1
            - name: Building the libelrond.a 
              run: make libelrond.a
            - name: Building and doing all tests
              run: make test-all a="-s -d yes"
