name: Build and test

on: [push]

jobs:
    build-and-test-linux:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04]
        steps:
            - uses: actions/checkout@v1
            - name: Building everything...
              run: make all -j4
            - name: Building and doing all tests...
              run: make test-all a="-s -d yes" -j4
