name: Build and test

on: [push]

jobs:
    build-and-test-linux:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04]
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Build the header only libraries
              run: make -f Headeronly.mk all
            - name: Run CMake
              run: mkdir build && cd build && cmake -G "Unix Makefiles" ..
            - name: Build everything
              run: cd build && make all -j4
            - name: Run tests
              run: cd build && make test
