on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release and Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Building everything
        run: make all -j4
      - name: Doing all tests
        run: make test-all a="-s -d yes" -j4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Second prerelease
          draft: true
          prerelease: true
      - name: Upload Release Asset libelrond.a
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libelrond.a
          asset_name: libelrond.a
          asset_content_type: application/x-archive
      - name: Upload Release Asset libelrond_ext.a
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libelrond_ext.a
          asset_name: libelrond_ext.a
          asset_content_type: application/x-archive
      - name: Upload Release Asset elrond.hpp
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/elrond.hpp
          asset_name: elrond.hpp
          asset_content_type: text/x-c++hdr
      - name: Upload Release Asset elrond_ext.hpp
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/elrond_ext.hpp
          asset_name: elrond_ext.hpp
          asset_content_type: text/x-c++hdr
      - name: Upload Release Asset elrond_test.hpp
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/elrond_test.hpp
          asset_name: elrond_test.hpp
          asset_content_type: text/x-c++hdr
